import React,{useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{Search,ShoppingBag,User,Heart,Menu,X,ArrowRight,Truck,ShieldCheck,Headphones,ChevronRight,Star,SlidersHorizontal,Plus,Minus,Trash2,ExternalLink,PackageSearch,Sparkles,Grid3X3,Check}from'lucide-react';
import'./style.css';

const products=[
['Auricolari Bluetooth TWS Pro','Audio',39.90,'-20%','https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=700&q=80'],
['Cuffie Wireless ANC Studio','Audio',79.90,'Novità','https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=700&q=80'],
['Speaker Bluetooth SoundBox','Audio',49.90,'-15%','https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=700&q=80'],
['Smartwatch Active X2','Smartwatch',69.90,'Bestseller','https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=700&q=80'],
['Smartwatch Fit Mini','Smartwatch',44.90,'-10%','https://images.unsplash.com/photo-1551816230-ef5deaed4a26?auto=format&fit=crop&w=700&q=80'],
['Caricatore GaN 65W','Energia',34.90,'Novità','https://images.unsplash.com/photo-1615526675159-e248c3021d3f?auto=format&fit=crop&w=700&q=80'],
['Power Bank 20.000 mAh','Energia',42.90,'-18%','https://images.unsplash.com/photo-1609592806596-b43bada2fabc?auto=format&fit=crop&w=700&q=80'],
['Cavo USB-C intrecciato 2m','Cavi',12.90,'','https://images.unsplash.com/photo-1591290619762-c588f652b5f3?auto=format&fit=crop&w=700&q=80'],
['Hub USB-C 8 in 1','Informatica',54.90,'Bestseller','https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=700&q=80'],
['Tastiera Meccanica RGB','Informatica',64.90,'-12%','https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=700&q=80'],
['Mouse Wireless Precision','Informatica',29.90,'','https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=700&q=80'],
['Lampada LED Smart Desk','Casa smart',36.90,'Novità','https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=700&q=80']
].map((p,i)=>({id:i+1,name:p[0],category:p[1],price:p[2],badge:p[3],image:p[4],rating:(4.5+(i%5)/10).toFixed(1)}));
const catalogUrl='https://elettronicafiorani.catonline.it';
const cats=[['Audio','Cuffie, auricolari e speaker'],['Smartwatch','Tecnologia sempre al polso'],['Energia','Caricatori e power bank'],['Informatica','Accessori per il tuo setup']];
function App(){const[query,setQuery]=useState(''),[cat,setCat]=useState('Tutti'),[sort,setSort]=useState('In evidenza'),[cart,setCart]=useState([]),[fav,setFav]=useState([]),[menu,setMenu]=useState(false),[cartOpen,setCartOpen]=useState(false);const filtered=useMemo(()=>{let a=products.filter(p=>(cat==='Tutti'||p.category===cat)&&p.name.toLowerCase().includes(query.toLowerCase()));if(sort==='Prezzo crescente')a.sort((a,b)=>a.price-b.price);if(sort==='Prezzo decrescente')a.sort((a,b)=>b.price-a.price);return a},[query,cat,sort]);const add=p=>setCart(c=>{let f=c.find(x=>x.id===p.id);return f?c.map(x=>x.id===p.id?{...x,q:x.q+1}:x):[...c,{...p,q:1}]});const count=cart.reduce((s,x)=>s+x.q,0),total=cart.reduce((s,x)=>s+x.price*x.q,0);return <>
<div className="top">Spedizione gratuita sopra i 49€ <span>•</span> Reso facile entro 30 giorni</div>
<header><a className="logo" href="#"><b>EF</b><span>ELETTRONICA<br/><strong>FIORANI</strong></span></a><nav className={menu?'open':''}><button className="navx" onClick={()=>setMenu(false)}><X/></button><a href="#novita">Novità</a><a href="#catalogo-completo">Catalogo completo</a><a href="#offerte">Offerte</a><a href="#servizi">Assistenza</a></nav><div className="actions"><button className="searchMobile" onClick={()=>document.querySelector('.search input').focus()}><Search/></button><button><User/></button><button><Heart/><i>{fav.length}</i></button><button onClick={()=>setCartOpen(true)}><ShoppingBag/><i>{count}</i></button><button className="hamb" onClick={()=>setMenu(true)}><Menu/></button></div></header>
<main><section className="hero"><div className="heroCopy"><small>TECNOLOGIA CHE TI SEMPLIFICA LA VITA</small><h1>Il futuro,<br/><em>a portata di mano.</em></h1><p>Scopri una selezione di elettronica affidabile, innovativa e pronta a seguirti ogni giorno.</p><a className="cta" href="#catalogo-completo">Esplora il catalogo <ArrowRight/></a><div className="trust"><span><b>4.9/5</b> recensioni clienti</span><span><b>+15 anni</b> di esperienza</span></div></div><div className="heroVisual"><div className="orb"></div><img src={products[3].image}/><div className="float f1">Autonomia<br/><b>7 giorni</b></div><div className="float f2"><span>●</span> Sempre connesso</div></div></section>
<section className="benefits" id="servizi"><div><Truck/><span><b>Spedizione veloce</b><small>Consegna in 24/48 ore</small></span></div><div><ShieldCheck/><span><b>Acquisti sicuri</b><small>Pagamenti protetti</small></span></div><div><Headphones/><span><b>Supporto reale</b><small>Esperti sempre disponibili</small></span></div></section>
<section className="fullCatalog" id="catalogo-completo"><div className="catalogHero"><div className="catalogCopy"><span className="eyebrow"><Sparkles/> IL CATALOGO, FATTO MEGLIO</span><h2>La tecnologia giusta.<br/><em>Senza perderti tra le pagine.</em></h2><p>Abbiamo ridisegnato il catalogo Fiorani dentro il sito: categorie chiare, prodotti selezionati e ricerca immediata. Tutto più bello, tutto più semplice.</p><div className="catalogActions"><a className="catalogCta" href="#catalogo">Scopri tutti i prodotti <ArrowRight/></a><a className="catalogLink" href={catalogUrl} target="_blank" rel="noreferrer">Consulta il listino ufficiale <ExternalLink/></a></div><div className="catalogChecks"><span><Check/> Selezione aggiornata</span><span><Check/> Acquisto assistito</span><span><Check/> Schede semplici</span></div></div><div className="catalogMosaic"><article className="mosaicMain"><img src={products[1].image} alt="Cuffie wireless"/><span>Audio</span><strong>Suono senza confini</strong><small>Scopri la selezione wireless</small></article><article><img src={products[3].image} alt="Smartwatch"/><span>Smartwatch</span></article><article className="mosaicBlue"><Grid3X3/><b>12</b><span>prodotti scelti<br/>per iniziare</span></article></div></div><div className="catalogBrowse"><div><PackageSearch/><span><small>ESPLORA IL CATALOGO</small><b>Scegli da dove iniziare</b></span></div><div className="browseCats">{cats.map((c,i)=><button key={c[0]} onClick={()=>{setCat(c[0]);location.hash='catalogo'}}><i>{String(i+1).padStart(2,'0')}</i><span><b>{c[0]}</b><small>{c[1]}</small></span><ChevronRight/></button>)}</div></div></section>
<section className="section"><div className="sectionHead"><div><small>ESPLORA PER CATEGORIA</small><h2>Tutto ciò che cerchi.<br/><em>Più facile da trovare.</em></h2></div><a href="#catalogo-completo">Vedi catalogo completo <ArrowRight/></a></div><div className="categories">{cats.map((c,i)=><button key={c[0]} onClick={()=>{setCat(c[0]);location.hash='catalogo'}}><div className={'catArt c'+i}>{i===0?'◖':i===1?'◉':i===2?'ϟ':'⌨'}</div><span><b>{c[0]}</b><small>{c[1]}</small></span><ChevronRight/></button>)}</div></section>
<section className="catalog" id="catalogo"><div className="sectionHead"><div><small>SCELTI PER TE</small><h2>I prodotti più amati</h2></div><p>Qualità, design e tecnologia: la nostra selezione per te.</p></div><div className="catalogTools"><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cerca nel catalogo..."/></div><div className="chips">{['Tutti',...cats.map(c=>c[0]),'Casa smart'].map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)}>{c}</button>)}</div><label><SlidersHorizontal/><select value={sort} onChange={e=>setSort(e.target.value)}><option>In evidenza</option><option>Prezzo crescente</option><option>Prezzo decrescente</option></select></label></div><div className="grid">{filtered.map(p=><article className="card" key={p.id}><div className="pic">{p.badge&&<span className="badge">{p.badge}</span>}<button className={fav.includes(p.id)?'liked':''} onClick={()=>setFav(f=>f.includes(p.id)?f.filter(x=>x!==p.id):[...f,p.id])}><Heart/></button><img src={p.image}/><button className="quick" onClick={()=>add(p)}>Aggiungi al carrello</button></div><small>{p.category}</small><h3>{p.name}</h3><div className="stars"><Star/> {p.rating}</div><div className="price">€ {p.price.toFixed(2).replace('.',',')}<button onClick={()=>add(p)}><Plus/></button></div></article>)}</div>{!filtered.length&&<div className="empty">Nessun prodotto trovato. Prova un'altra ricerca.</div>}</section>
<section className="promo" id="offerte"><div><small>SOLO ONLINE</small><h2>Più tecnologia.<br/><em>Meno pensieri.</em></h2><p>Iscriviti alla newsletter e ricevi il <b>10% di sconto</b> sul tuo primo ordine.</p><form onSubmit={e=>e.preventDefault()}><input type="email" required placeholder="La tua email"/><button>Ottieni lo sconto <ArrowRight/></button></form></div><div className="promoArt">10<sup>%</sup><span>WELCOME<br/>DISCOUNT</span></div></section></main>
<footer><a className="logo light"><b>EF</b><span>ELETTRONICA<br/><strong>FIORANI</strong></span></a><p>Tecnologia scelta con cura,<br/>assistenza fatta da persone.</p><div><b>Acquista</b><a>Catalogo</a><a>Novità</a><a>Offerte</a></div><div><b>Supporto</b><a>Contatti</a><a>Spedizioni e resi</a><a>FAQ</a></div><small>© 2026 Elettronica Fiorani · Privacy · Cookie</small></footer>
<div className={'overlay '+(cartOpen?'show':'')} onClick={()=>setCartOpen(false)}></div><aside className={'drawer '+(cartOpen?'show':'')}><div className="drawerHead"><h2>Il tuo carrello <small>{count}</small></h2><button onClick={()=>setCartOpen(false)}><X/></button></div>{cart.length===0?<div className="cartEmpty"><ShoppingBag/><h3>Il carrello è vuoto</h3><p>Scopri la nostra selezione high-tech.</p><button onClick={()=>setCartOpen(false)}>Vai al catalogo</button></div>:<><div className="cartList">{cart.map(x=><div className="cartItem"><img src={x.image}/><div><b>{x.name}</b><span>€ {x.price.toFixed(2)}</span><div><button onClick={()=>setCart(c=>c.map(y=>y.id===x.id?{...y,q:Math.max(1,y.q-1)}:y))}><Minus/></button>{x.q}<button onClick={()=>add(x)}><Plus/></button></div></div><button onClick={()=>setCart(c=>c.filter(y=>y.id!==x.id))}><Trash2/></button></div>)}</div><div className="checkout"><div><span>Totale</span><b>€ {total.toFixed(2).replace('.',',')}</b></div><button>Vai al checkout <ArrowRight/></button><small>Spedizione gratuita sopra i 49€</small></div></>}</aside>
</>};createRoot(document.getElementById('root')).render(<App/>);
